#!/usr/bin/env bash
#
# Summary: Show out of date installed packages
#
# Usage: pm outdated
#

set -e
# https://stackoverflow.com/a/677212
if command -v python3 >/dev/null 2>&1; then
  pip3 list -o --format freeze | awk -F"==" '{print $1}'
else
  pip list -o --format freeze | awk -F"==" '{print $1}'
fi
