#!/usr/bin/env bash
#
# Summary:
#    Update all outdated packages
#
# Usage: pm update
#
set -e

# https://stackoverflow.com/a/677212
if command -v python3 >/dev/null 2>&1; then
    pip3 install --upgrade pip
    for pkg in $(pm-pip outdated);
    do
      pip3 install --upgrade ${pkg}
    done
else
    pip list --outdated
    for pkg in $(pm-pip outdated);
    do
      pip3 install --upgrade ${pkg}
    done
fi

