#!/usr/bin/env bash
#
# Summary: Display all installed packages
#
# Usage: pm-pip list

set -e

echo "** Pip **"
# https://stackoverflow.com/a/677212
if command -v python3 >/dev/null 2>&1; then
    pip3 list
else
    pip list
fi
